image: docker:stable

stages:
- image-build
- build
- test
- deploy

services: 
- docker:dind

build-docker-image:
  before_script:
  - docker login -u "$CI_REGISTRY_USERNAME" -p "$CI_REGISTRY_PASSWORD"
  stage: image-build
  script:
  - docker build -t alura-gitlab-ci .
  - docker tag alura-gitlab-ci gpoleze/alura-gitlab-ci:latest
  - docker push gpoleze/alura-gitlab-ci:latest

build-project:
  stage: build
  image: gpoleze/alura-gitlab-ci:latest
  dependencies:
  - build-docker-image
  tags:
  - alura-executor
  script:
  - echo "testing Runner"